name: AWS Terraform Deployment

on:
  push:
    branches:
      - dev

jobs:
  plan:
    name: Plan Terraform Changes
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Initialize Terraform
        working-directory: ./aws
        run: terraform init

      - name: Plan Terraform
        working-directory: ./aws
        run: terraform plan -out=tfplan

      - name: Save Terraform Plan Output
        working-directory: ./aws
        run: terraform show -json tfplan > plan.json

      - name: Upload Plan for Review
        uses: actions/upload-artifact@v3
        with:
          name: terraform-plan
          path: ./aws/plan.json
