name: AWS Terraform Deployment

on:
  push:
    branches:
      - main

jobs:
  plan:
    name: Plan Terraform Changes
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Initialize Terraform
        working-directory: ./aws
        run: terraform init

      - name: Plan Terraform
        working-directory: ./aws
        run: terraform plan -out=tfplan

      - name: Upload Terraform Plan
        uses: actions/upload-artifact@v3
        with:
          name: terraform-plan
          path: ./aws/tfplan

  manual_approval:
    name: Wait for Manual Approval
    needs: plan
    runs-on: ubuntu-latest

    steps:
      - name: Awaiting Manual Approval
        run: echo "Review the Terraform plan and approve this workflow to proceed."

  apply:
    name: Apply Terraform Changes
    needs: manual_approval
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Download Terraform Plan
        uses: actions/download-artifact@v3
        with:
          name: terraform-plan
          path: ./aws

      - name: Apply Terraform Plan
        working-directory: ./aws
        run: terraform apply -auto-approve tfplan
