name: AWS Terraform Deployment

on:
  push:
    branches:
      - main

jobs:
  plan:
    name: Plan Terraform Changes
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Initialize Terraform
        working-directory: ./aws
        run: terraform init

      - name: Plan Terraform Changes
        working-directory: ./aws
        run: terraform plan

      - name: Upload Plan for Review (optional)
        uses: actions/upload-artifact@v3
        with:
          name: terraform-plan
          path: ./aws/plan.json

  manual_approval:
    name: Wait for Manual Approval
    needs: plan
    runs-on: ubuntu-latest

    steps:
      - name: Manual Approval Required
        run: |
          echo "Please review the Terraform plan and approve this workflow."
          echo "Go to the Actions tab and click 'Approve and run' to continue."

  apply:
    name: Apply Terraform Changes
    needs: manual_approval
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Apply Terraform Changes
        working-directory: ./aws
        run: terraform apply -auto-approve
